"""
Demonstration of Step C4: Dynamic Citation Compiler & Evidence Graph in Aegis Research OS.
"""

import json
from retriever import HybridRAGEngine, DynamicCitationCompiler


def run_c4_demo():
    print("=== Aegis Research OS - Step C4 Dynamic Citation Compiler & Evidence Graph ===")

    engine = HybridRAGEngine(collection_name="aegis_c4_demo")
    engine.reset()

    # 1. Ingest research document
    research_doc = """# Aegis OS Architecture Specification

SECTION: Core Security
Aegis Research OS enforces strict containerized isolation for python sandbox code execution.
Prompt injection defense mechanisms audit all tool calls before execution.

SECTION: Hybrid Live RAG
Developer C implemented ChromaDB for dense vector search and BM25 for keyword scoring.
Reciprocal Rank Fusion (RRF) dynamically calculates combined ranks for retrieved passages.
"""

    print("\n[1] Ingesting Research Document into RAG Engine & Evidence Graph...")
    engine.ingest_document(text=research_doc, doc_id="doc_aegis_arch_v1", metadata={"source_path": "/docs/aegis_arch.pdf"})
    print(f"[OK] Ingested document. Evidence Graph Node Count: {engine.evidence_graph.node_count()}")

    # 2. Markdown Report Draft generated by Developer A's orchestrator
    draft_markdown = """# Research Investigation Report

## Executive Summary
Aegis Research OS enforces strict containerized isolation for python sandbox code execution [1].
Prompt injection defense mechanisms audit all tool calls before execution [^2].

## RAG & Retrieval Performance
Developer C implemented ChromaDB for dense vector search and BM25 for keyword scoring [Citation: doc_aegis_arch_v1].
The system operates on quantum hardware at absolute zero temperature [3].
"""

    print("\n[2] Parsing Markdown Draft and Compiling Dynamic Citation JSON...")
    citation_map = engine.compile_citations(markdown_draft=draft_markdown)

    print(f"\n[+] Total Claims Analyzed: {citation_map['total_claims']}")
    print(f"[+] Verified Claims Count: {citation_map['verified_claims_count']}")
    print(f"[+] Unverified Claims Count: {citation_map['unverified_claims_count']}")
    print(f"[+] Overall Verification Rate: {citation_map['verification_rate'] * 100}%")

    print("\n[3] Compiled Citation Entries:")
    for c in citation_map["citations"]:
        print(f"\n--- Citation ID: {c['citation_id']} ({c['marker']}) ---")
        print(f"Claim: \"{c['claim_text']}\"")
        print(f"Status: {c['verification_status'].upper()} (Confidence: {c['confidence']})")
        if c['verification_status'] == 'verified':
            print(f"Supporting Sources: {c['provenance']['source_paths']}")
            print(f"Supporting Quotes: {c['provenance']['raw_quotes'][:1]}")

    print("\n[4] Writing state results to state.json...")
    with open("state.json", "w", encoding="utf-8") as f:
        json.dump({
            "project_name": "Aegis Research OS",
            "active_task_id": "task_c4_citation_compiler",
            "query": "Aegis security sandbox RAG execution",
            "markdown_draft": draft_markdown,
            "retrieval_config": {"top_k": 5, "dense_weight": 0.5, "sparse_weight": 0.5},
            "search_results": [],
            "deduplicated_results": [],
            "tracked_conflicts": [],
            "citations": [],
            "status": "idle"
        }, f, indent=2)

    updated_state = engine.sync_with_state("state.json")
    print(f"[OK] state.json status: {updated_state['status']}")
    print(f"[OK] state.json citations count: {len(updated_state['citations'])}")
    print(f"[OK] state.json verification_rate: {updated_state['citation_summary']['verification_rate']}")

    print("\n=== Step C4 Dynamic Citation Compiler demo completed successfully! ===")


if __name__ == "__main__":
    run_c4_demo()
